Improvements/database project change in binaries
dotnetnicaragua/BlogNetNicaragua pull request #5
Opened 2023-09-12 01:30 UTC by pac09

Branch to include the SQL project to track the changes in database structure, the changes in the web project (AppData folder) points now to the MSSQLCloud instance.

2023-09-12 04:40 UTC, rubone requested changes
Solo un comentario sobre data sensible. No hay que trackearla en el repo, pls

2023-09-12 04:40 UTC, rubone commented on src/BlogNetNicaragua.Web/App_Data/Sites/Default/appsettings.json
> +  "ConnectionString": "Server=SQL5111.site4now.net;Database=db_a7d2a8_blognetnicaragua;User Id=db_a7d2a8_blognetnicaragua_admin;Password=H3jlsb3rg!",
Hey bro! Creo que no debemos manejar data sensible (user & password) trackeada en el repo.

2023-10-01 06:36 UTC, pac09 commented on src/BlogNetNicaragua.Web/App_Data/Sites/Default/appsettings.json
> +  "ConnectionString": "Server=SQL5111.site4now.net;Database=db_a7d2a8_blognetnicaragua;User Id=db_a7d2a8_blognetnicaragua_admin;Password=H3jlsb3rg!",
Cierto, este archivo esta en la carpeta App_Data, esta oculto por el Visual Studio. Olvide que ahi guarda conexiones Orchard.

2023-10-03 14:41 UTC, rubone approved these changes
![31173349](https://github.com/dotnetnicaragua/BlogNetNicaragua/assets/1043247/8092bd96-87e4-4402-a4f9-6460a387b805)

2023-10-03 14:54 UTC, merged